// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/song.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8821277811218544115),
    name: 'Song',
    lastPropertyId: const obx_int.IdUid(14, 7313911926261287548),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6488944693296695625),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 563570291174276779),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6167011765445137370),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6883516046890042815),
        name: 'artist',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5626970840388193135),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6950630416761939253),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5477606557243311434),
        name: 'vocalPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4252804410467501000),
        name: 'instrumentalPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5411544786149217022),
        name: 'audioImgUri',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2231009584145218245),
        name: 'lyrics',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6988265277597161522),
        name: 'amplitude',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 732563055709382247),
        name: 'timestampLyrics',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 909824457456036851),
        name: 'createdDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7313911926261287548),
        name: 'recentDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8821277811218544115),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Song: obx_int.EntityDefinition<Song>(
      model: _entities[0],
      toOneRelations: (Song object) => [],
      toManyRelations: (Song object) => {},
      getId: (Song object) => object.id,
      setId: (Song object, int id) {
        object.id = id;
      },
      objectToFB: (Song object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final artistOffset = fbb.writeString(object.artist);
        final filePathOffset = fbb.writeString(object.filePath);
        final vocalPathOffset = fbb.writeString(object.vocalPath);
        final instrumentalPathOffset = fbb.writeString(object.instrumentalPath);
        final audioImgUriOffset = fbb.writeString(object.audioImgUri);
        final lyricsOffset = fbb.writeString(object.lyrics);
        final amplitudeOffset = fbb.writeString(object.amplitude);
        final timestampLyricsOffset = fbb.writeString(object.timestampLyrics);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, artistOffset);
        fbb.addInt64(4, object.duration);
        fbb.addOffset(5, filePathOffset);
        fbb.addOffset(6, vocalPathOffset);
        fbb.addOffset(7, instrumentalPathOffset);
        fbb.addOffset(8, audioImgUriOffset);
        fbb.addOffset(9, lyricsOffset);
        fbb.addOffset(10, amplitudeOffset);
        fbb.addOffset(11, timestampLyricsOffset);
        fbb.addInt64(12, object.createdDate.millisecondsSinceEpoch);
        fbb.addInt64(13, object.recentDate.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final artistParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final audioImgUriParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final lyricsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final amplitudeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final timestampLyricsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final vocalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final instrumentalPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final createdDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final recentDateParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
        );
        final object = Song(
          id: idParam,
          uuid: uuidParam,
          title: titleParam,
          artist: artistParam,
          duration: durationParam,
          filePath: filePathParam,
          audioImgUri: audioImgUriParam,
          lyrics: lyricsParam,
          amplitude: amplitudeParam,
          timestampLyrics: timestampLyricsParam,
          vocalPath: vocalPathParam,
          instrumentalPath: instrumentalPathParam,
          createdDate: createdDateParam,
          recentDate: recentDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Song] entity fields to define ObjectBox queries.
class Song_ {
  /// See [Song.id].
  static final id = obx.QueryIntegerProperty<Song>(_entities[0].properties[0]);

  /// See [Song.uuid].
  static final uuid = obx.QueryStringProperty<Song>(_entities[0].properties[1]);

  /// See [Song.title].
  static final title = obx.QueryStringProperty<Song>(
    _entities[0].properties[2],
  );

  /// See [Song.artist].
  static final artist = obx.QueryStringProperty<Song>(
    _entities[0].properties[3],
  );

  /// See [Song.duration].
  static final duration = obx.QueryIntegerProperty<Song>(
    _entities[0].properties[4],
  );

  /// See [Song.filePath].
  static final filePath = obx.QueryStringProperty<Song>(
    _entities[0].properties[5],
  );

  /// See [Song.vocalPath].
  static final vocalPath = obx.QueryStringProperty<Song>(
    _entities[0].properties[6],
  );

  /// See [Song.instrumentalPath].
  static final instrumentalPath = obx.QueryStringProperty<Song>(
    _entities[0].properties[7],
  );

  /// See [Song.audioImgUri].
  static final audioImgUri = obx.QueryStringProperty<Song>(
    _entities[0].properties[8],
  );

  /// See [Song.lyrics].
  static final lyrics = obx.QueryStringProperty<Song>(
    _entities[0].properties[9],
  );

  /// See [Song.amplitude].
  static final amplitude = obx.QueryStringProperty<Song>(
    _entities[0].properties[10],
  );

  /// See [Song.timestampLyrics].
  static final timestampLyrics = obx.QueryStringProperty<Song>(
    _entities[0].properties[11],
  );

  /// See [Song.createdDate].
  static final createdDate = obx.QueryDateProperty<Song>(
    _entities[0].properties[12],
  );

  /// See [Song.recentDate].
  static final recentDate = obx.QueryDateProperty<Song>(
    _entities[0].properties[13],
  );
}
